export const Indicadores = {
    NOTIFICACOES_ENVIADAS: "NOTIFICACOES_ENVIADAS",
    NOTIFICACOES_RECEBIDAS: "NOTIFICACOES_RECEBIDAS",
    CONEXOES_ATUAIS: "CONEXOES_ATUAIS",
    CONEXOES_NOVAS: "CONEXOES_NOVAS"
}