export enum Periodos {
    HOJE = 'HOJE',
    SEMANA_ATUAL = 'SEMANA_ATUAL',
    ULTIMOS_SETE_DIAS = 'ULTIMOS_SETE_DIAS',
    ULTIMOS_QUINZE_DIAS = 'ULTIMOS_QUINZE_DIAS',
    ULTIMOS_TRINTA_DIAS = 'ULTIMOS_TRINTA_DIAS',
    MES_ATUAL = 'MES_ATUAL',
    INTERVALO = 'INTERVALO'
}